export const LIST_CART_LOADED = 'LIST_CART_LOADED';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const SET_PRODUCT = 'SET_PRODUCT';
export const UPDATE_PRODUCT_ON_CART = 'UPDATE_PRODUCT_ON_CART';
